### ISSUE TITLE
Trier les documents et les intervenants par date

### ISSUE THREAD

**Issue by guillaume-garcia** [medialab/reanalyse#34]
Dans le meta_document.csv on référence la date de création du document ; ce serait bien d'afficher l'information sur le site, au niveau de la Table des documents, de manière à pouvoir trier les documents de l'enquête en fonction de leur date (l'information sera en partie redondante avec la colonne ResearchPhase
Il faudrait faire pareil dans le document meta_speakers.csv : rajouter la date de l'entretien ou de l'observation pour la catégorie "speakers" et la catégorie "protagonists", de manière là aussi à pouvoir trier chronologiquement dans la Table des intervenants

**Comment by pierrejdlf** [comment]
ok pour les docs (*date et *location désormais OBLIGATOIRES dans meta_documents.csv)

pour les spk : *date ne sera pas forcément dans meta_speakers.csv... à suivre

ps: je rajoute le label "Normalisation", car dépend fortement de ce qu'on fige dans les meta_*.csv
