### ISSUE TITLE
full text search engine 

### ISSUE THREAD

**Issue by paulgirard** [medialab/reanalyse#44]
I quote Guillaume : 
- elle ne fonctionne pas sur la page Overview
  même si on peut se demander à quoi servirait une telle fonction sur cette page

A la place s’affiche le message d’erreur suivant :

DoesNotExist at /e/40/search/

Speaker matching query does not exist.

Request Method:
Request URL:
Django Version:
Exception Type:
Exception Value:
Exception Location:
Python Executable:
Python Version:
Python Path:

GET
http://quali.dime-shs.sciences-po.fr/bequali/e/40/search/?q=france
1.4
DoesNotExist
Speaker matching query does not exist.
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 366
/usr/bin/python
2.7.3
['/usr/local/lib/python2.7/dist-packages/pythonsolr-1.0-py2.7.egg',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-linux2',
'/usr/lib/python2.7/lib-tk',
'/usr/lib/python2.7/lib-old',
'/usr/lib/python2.7/lib-dynload',
'/usr/local/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages/gtk-2.0',
'/usr/lib/pymodules/python2.7',
'/var/opt/bequali',
'/var/opt']

Server time: mar, 20 Nov 2012 15:49:45 +0100
- elle ne fonctionne pas non plus sur la page « Documents »
  qu’il s’agisse du tableau récapitulatif des documents disponibles, ou d’un document en
  particulier – fichiers PDF, CSV et TEI y compris
  A chaque fois le même message d’erreur suivant s’affiche :

DoesNotExist at /e/40/search/

Speaker matching query does not exist.

Request Method:

Request URL:

Django Version:

Exception Type:

Exception Value:

Exception Location:

GET

http://quali.dime-shs.sciences-po.fr/bequali/e/40/search/?q=recherche

1.4

DoesNotExist

Speaker matching query does not exist.

/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 366

Python Executable:

Python Version:

Python Path:

/usr/bin/python

2.7.3

['/usr/local/lib/python2.7/dist-packages/pythonsolr-1.0-py2.7.egg',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-linux2',
'/usr/lib/python2.7/lib-tk',
'/usr/lib/python2.7/lib-old',
'/usr/lib/python2.7/lib-dynload',
'/usr/local/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages/gtk-2.0',
'/usr/lib/pymodules/python2.7',
'/var/opt/bequali',
'/var/opt']

Server time: mar, 20 Nov 2012 15:00:04 +0100
- si on se loggue en mode Explore ne fonctionne pas non plus

Le même message d’erreur s’affiche :

DoesNotExist at /e/40/search/

Speaker matching query does not exist.

Request Method:
Request URL:
Django Version:
Exception Type:
Exception Value:
Exception Location:
Python Executable:
Python Version:
Python Path:

GET
http://quali.dime-shs.sciences-po.fr/bequali/e/40/search/?q=finist%C3%A8re
1.4
DoesNotExist
Speaker matching query does not exist.
/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 366
/usr/bin/python
2.7.3
['/usr/local/lib/python2.7/dist-packages/pythonsolr-1.0-py2.7.egg',
'/usr/lib/python2.7',
'/usr/lib/python2.7/plat-linux2',
'/usr/lib/python2.7/lib-tk',
'/usr/lib/python2.7/lib-old',
'/usr/lib/python2.7/lib-dynload',
'/usr/local/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages',
'/usr/lib/python2.7/dist-packages/gtk-2.0',
'/usr/lib/pymodules/python2.7',
'/var/opt/bequali',
'/var/opt']
Server time: mar, 20 Nov 2012 16:03:40 +0100

**Comment by pierrejdlf** [comment]
1) la fonction recherche à gauche est la même partout (quelle que soit la page)

2) l'index solr est mis à jour à chaque création/suppression de doc/spk django.
les bugs "no matching query"...
(ie. dans l'index solr des références à des doc/spk qui ne se trouvent pas dans la base de donnée postgresql)
... correspondent donc à des cas particuliers de développement (enquête mal chargée sur le site par ex.)
ces bugs n'apparaitront pas si toutes les enquêtes sont bien chargées

**Comment by paulgirard** [comment]
Dans le cas de telles erreurs il faut intercepter l'erreur et prévenir les utilisateurs et si nécessaire demander au administrateur de recharger l'enquête.

Merci d'éclaircir les conditions d'apparition de ce bug : 
est ce que c'est toute l'enquete qu'il faut recharger ou simplement la viz ?

**Comment by pierrejdlf** [comment]
ce bug (désormais intercepté et annoncé dans les logs) apparaitra dans le cas:
- chargement d'une enquête jusqu'au bout, sans problème
- suppression de cette même enquête (prend du temps, car djgo doit supprimer tous les objets associés)
- ... j'ai gardé la page de l'enquête (encoursdesuppression) ouverte dans mon navigateur, et je recherche qq chose

c'est-à-dire jamais, car l'accès à une enquête en cours de suppression ne sera plus possible (aujourd'hui possible, pour debug-dev temporaire)

NB: la recherche ne fait pas intervenir de viz

concernant l'index solr, il est désormais mis à jour à la fin du chrgmt d'une enquête, cf:
https://github.com/medialab/reanalyse/issues/49
