### ISSUE TITLE
Check visualization can only be seen from its survey

### ISSUE THREAD

**Issue by paulgirard** [medialab/reanalyse#45]
I quote Guillaume : 
- Pour l’enquête A le site « emprunte » des visualisations de l’enquête B ; autrement dit des
  visualisations de l’enquête B « glissent » vers l’enquête A

Et l’enquête B semble privée de certaines de ses visualisations.

-le comptage des créations / suppressions de visualisations ne fonctionne pas bien.

**Comment by pierrejdlf** [comment]
le décompte des visualisation indique désormais `(2 / 87)`, ie:
`(nb viz publiques / nb de viz total)`
