### ISSUE TITLE
Delete survey process buggy ? 

### ISSUE THREAD

**Issue by paulgirard** [medialab/reanalyse#46]
1.7- Beaucoup de mal à supprimer les enquêtes en mode admin

l’enquête semble supprimée mais quand on actualise la page en cliquant sur l’onglet
Enquête, l’enquête supprimée réapparaît ; il faut parfois cliquer plusieurs fois avant que
l'enquête ne soit réellement supprimée.

**Comment by paulgirard** [comment]
A FAIRE : Confirmation de suppression :  Attention on va tout virer  et efectivemetn effacer toute trace (ficheir + BDD)

option : ajouter la question souhaitez vous télécharger une archive avant ?

**Comment by pierrejdlf** [comment]
clicking delete now shows a popup to confirm it
todo: option for download - in another issue

**Comment by paulgirard** [comment]
should delete the files from filesystem

**Comment by pierrejdlf** [comment]
done !

note that you can't delete "loading..." studies anymore
... only "already loaded" or "failed" studies

**Comment by pierrejdlf** [comment]
loading/deleting studies are only visible by admins (permission can_make)
... with different background colors in the list
deleting now also shows completion pourcentage
